spring:
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

  database:
    driverClassName: org.postgresql.Driver

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/db_cardapio
    username: postgres
    password: root
